#pragma once

#include "caai_slam/core/types.hpp"
#include "caai_slam/core/config.hpp"
#include "caai_slam/frontend/keyframe.hpp"
#include "caai_slam/mapping/covisibility_graph.hpp"

#include <deque>
#include <shared_mutex>
#include <unordered_set>

namespace caai_slam {
    /**
     * @brief Manages the active window of keyframes and map points.
     * 
     * Synchronized with GTSAM's IncrementalFixedLagSmoother.
     * Handles:
     * - Insertion of new keyframes
     * - Culling of marginalized keyframes
     * - Triangulation and management of map points
     * - Spatial queries for tracking
     */
    class local_map {
    private:
        config _config;

        // Core containers
        std::deque<std::shared_ptr<keyframe>> active_keyframes;
        std::unordered_set<std::shared_ptr<map_point>> active_map_points;

        // Topology
        covisibility_graph covis_graph;

        // Thread safety
        mutable std::shared_mutex mutex; // R/W lock

        // Helpers
        bool is_point_in_frustrum(const vec3& pos_world, const se3& t_cam_world) const;

    public:
        EIGEN_MAKE_ALIGNED_OPERATOR_NEW

        explicit local_map(const config& cfg) : _config(cfg) {}

        // =========================================================================
        // Keyframe management
        // =========================================================================

        /**
         * @brief Add a new keyframe to the local map window.
         * 
         * - Adds to deque
         * - Updates covisbility graph
         * - Adds new map points generated by this keyframe
         * 
         * @param kf keyframe to be added to the local map.
         */
        void add_keyframe(const std::shared_ptr<keyframe>& kf);

        /**
         * @brief Prune keyframes older than the lag time (matches GTSAM marginalization).
         * 
         * @param current_timestamp The timestamp of the newest frame.
         */
        void prune_old_keyframes(const double current_timestamp);

        /**
         * @brief Get all keyframes currently in the optimization window.
         * 
         * @return Vector of all keyframes currently in the optimization window.
         */
        std::vector<std::shared_ptr<keyframe>> get_all_keyframes() const;

        /**
         * @brief Get keyframes connected to the given frame via covisibility.
         * 
         * Used to determine which frames to optimize in local BA.
         * 
         * @param kf Keyframe to determine covisible keyframes from.
         * @param min_shared_points Minimum number of map points shared between keyframes.
         * 
         * @return Vector of covisible keyframes.
         */
        std::vector<std::shared_ptr<keyframe>> get_covisible_keyframes(const std::shared_ptr<keyframe>& kf, const int32_t min_shared_points = 15) const;

        // =========================================================================
        // Map point management
        // =========================================================================

        /**
         * @brief Add a newly triangulated map point.
         * 
         * @param mp map point to be added.
         */
        void add_map_point(const std::shared_ptr<map_point>& mp);

        /**
         * @brief Fuse duplicate map points (e.g., after loop closure or local mapping).
         * 
         * Merges 'victim' into 'target' and removes 'victim'.
         * 
         * @param target map point to be merged into.
         * @param victim map point to be fused and discarded.
         */
        void fuse_map_points(std::shared_ptr<map_point>& target, std::shared_ptr<map_point>& victim);

        /**
         * @brief Remove bad map points (outliers, low observation count).
         */
        void cull_map_points();

        // =========================================================================
        // Queries
        // =========================================================================

        /**
         * @brief Find map points visible in the current camera view.
         * 
         * Used by the frontend to project the map into the current frame for tracking.
         * 
         * @param pose_world_cam Current camera pose (t_world_cam).
         * 
         * @return Vector of visible map points.
         */
        std::vector<std::shared_ptr<map_point>> get_map_points_in_view(const se3& pose_world_cam) const;

        size_t num_keyframes() const;
        size_t num_map_points() const;
    };

} // namespace caai_slam